name: health-check-service
services:
  producer:
    network_mode: host
    image: producer
    build:
      context: health_check_service
      dockerfile: Dockerfile

    env_file: .env

  consumer:
    image: consumer
    build:
      context: consumer_health_check_service
      dockerfile: Dockerfile

    env_file: .env
    network_mode: host
