# Default values for HealthCheckService.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

tests:
  enabled: false

image:
  name:  # can either be 'consumer' or 'producer' for this local environment
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

#imagePullSecrets: [ ] # not configured for now

nameOverride: ""
fullnameOverride: ""

podAnnotations: { }
podLabels: { }

# must be overwritten by the consumer or producer values file
configmap:
  nameOverride:
  data:
    KAFKA_BOOTSTRAP_SERVERS: '' # fill by CLI
    KAFKA_TOPIC: '' # fill by CLI
    KAFKA_CONSUMER_GROUP_ID: '' # fill by CLI
    HEALTHCHECK_SERVICE_DEBUG: "true"
    CONSUMER_HEALTHCHECK_SERVICE_DEBUG: "true"

service:
  type: ClusterIP
  port:

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1